spring:
  application:
    name: bookable
  datasource:
    url: jdbc:postgresql://localhost:5432/bookable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true